version: "3.8"
services:
  nextjs:
    extends:
      file: docker-compose.base.yml
      service: nextjs
    container_name: nextjs_dev
    build:
      target: production
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: npm start

  nginx:
    image: nginx:alpine
    depends_on:
      - nextjs
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
